framework:
    default_locale: '%locale%'
    translator:
        fallbacks:
            - 'en'

# php_translation
translation:
    webui:
        enabled: true
    locales: ['en', 'nl', 'es', 'fr', 'de', 'pl', 'it', 'pt_BR']
    edit_in_place:
        enabled: false
    configs:
        bolt:
            dirs: ["%kernel.project_dir%/vendor/bolt/core/templates", "%kernel.project_dir%/src"]
            output_dir: "%kernel.project_dir%/vendor/bolt/core/translations"

