twig:
    debug: '%kernel.debug%'
    strict_variables: true
    form_themes:
        - 'form/layout.twig'
        - 'form/fields.twig'
    paths:
        # Since the name of the theme folder is dynamic, we shouldn't set it here, but dynamically
        # See TwigAwareController::setTwigLoader()
        # '%kernel.project_dir%/public/theme/%bolt.theme%': ''
        '%kernel.project_dir%/vendor/bolt/core/templates/': 'bolt'
    default_path: '%kernel.project_dir%/vendor/bolt/core/templates'
    globals:
        'config': '@Bolt\Configuration\Config'
