cacheMaxAge: 30
itemAmount: 20

# Set the key, to prevent people from trying to DDOS your server by triggering
# /bolt/extends/rssaggregate a lot.
key: aGhgdhTRV35FS

import_taxonomy: tags
ignore_taxonomy_terms: [ php, programming, uncategorized, desktop-wallpaper, javascript ]

feeds:
  symfony:
    name: "Symfony blog"
    title: "The Symfony blog"
    url: "https://symfony.com/blog/"
    feed: "https://feeds.feedburner.com/symfony/blog"
    compact: true
  laracasts:
    url: https://laracasts.com/feed
    name: Laracasts
    feed: https://laracasts.com/feed
    title: Laracasts
    compact: true
  laravelnews:
    url: https://laravel-news.com
    name: Laravel News
    feed: https://feed.laravel-news.com/
    title: Laravel News
    compact: true
  scotchio:
    url: https://www.scotch.io/
    name: Scotch.io
    feed: https://scotch.io/feed
    title: Scotch.io
    compact: true
  signalvnoise:
    url: https://m.signalvnoise.com?source=rss----668e14b18fb1---4
    name: Signal vs. Noise
    feed: https://signalvnoise.com/posts.rss
    title: Signal vs. Noise
    compact: true
  googleblog:
    url: https://security.googleblog.com/
    name: Google Online Security Blog
    feed: https://feeds.feedburner.com/GoogleOnlineSecurityBlog
    title: Google Online Security Blog
    compact: true
    active: false
  tutorialzine:
    url: https://tutorialzine.com
    name: Tutorialzine
    feed: https://feeds.feedburner.com/Tutorialzine
    title: Tutorialzine
    active: false
  derekrethans:
    name: "Derick Rethans"
    title: "Derick Rethans' blog'"
    url: "https://derickrethans.nl/"
    feed: "https://derickrethans.nl/feed.xml"
  paulmjones:
    name: "Paul M. Jones"
    title: "There are no solutions, only tradeoffs."
    url: "http://paul-m-jones.com/"
    feed: "http://paul-m-jones.com/atom.xml"
  mwop:
    url: "https://mwop.net/blog"
    title: "phly, boy, phly: matthew weier o'phinney"
    name: "Matthew Weier o'Phinney"
    feed: "https://mwop.net/blog/rss.xml"
  brandonsavage:
    name: "Brandon Savage"
    url: "https://www.brandonsavage.net/blog/"
    feed: "https://www.brandonsavage.net/feed/"
    title: "Brandon Savage's blog"
    active: false # Feed doesn't download
  erikaheidi:
    url: "https://erikaheidi.com/"
    title: "Erika Heidi's blog"
    name: "Erika Heidi"
    feed: "https://feeds.feedburner.com/erikaheidi/blog" # https://erikaheidi.com/entries/rss/feed.rss"
    active: false
  calevans:
    name: "Cal Evans"
    title: "Cal Evans - Postcards From My Life"
    url: "https://blog.calevans.com/"
    feed: "https://feeds.feedburner.com/PostcardsFromMyLife" # "https://blog.calevans.com/feed/"
  chrishartjes:
    name: "Chris Hartjes"
    title: "@TheKeyboard"
    url: "https://www.littlehart.net/atthekeyboard/"
    feed: "https://www.littlehart.net/atthekeyboard/atom.xml"
  lornajane:
    name: "Lorna Jane"
    title: "Lorna Jane's blog"
    url: "https://www.lornajane.net/blog"
    feed: "https://www.lornajane.net/feed"
  ircmaxell:
    name: "Ircmaxell"
    title: "Ircmaxell's blog"
    url: "https://blog.ircmaxell.com/"
    feed: "https://blog.ircmaxell.com/feeds/posts/default?alt=rss"
  philsturgeon:
    name: "Phil Sturgeon"
    title: "Phil Sturgeon's blog"
    url: "https://phil.tech/"
    feed: "https://phil.tech/feed.xml" # "https://philsturgeon.uk/blog/rss/all.rss"
  skoop:
    name: "Stefan Koopmanschap"
    title: "Skoop.dev"
    url: "https://skoop.dev/"
    feed: "https://skoop.dev/atom.xml"
  krakjoe:
    name: "Krakjoe"
    title: "Musings, ninja ones"
    url: "https://blog.krakjoe.ninja/"
    feed: "https://blog.krakjoe.ninja/feeds/posts/default"
  rosstuck:
    name: "Ross Tuck"
    title: "Ross Tuck's weblog"
    url: "https://rosstuck.com/"
    feed: "https://rosstuck.com/feed.xml"
    active: false
  fabpot:
    name: "Fabien Potencier"
    title: "Fabien Potencier's blog"
    url: "https://fabien.potencier.org/"
    feed: "https://feeds.fabien.potencier.org/aidedecamp"
    active: false
  matthiasnoback:
    name: "Matthias Noback"
    title: "Matthias Noback's blog"
    url: "https://matthiasnoback.nl//"
    feed: "https://matthiasnoback.nl/atom.xml"
  taylorotwell:
    name: "Taylor Otwell"
    title: "Taylor Otwell's blog"
    url: "https://medium.com/@taylorotwell"
    feed: "https://medium.com/feed/@taylorotwell"
  evertpot:
    name: "Evert Pot"
    title: "Het Bijstere Spoor"
    url: "https://evertpot.com"
    feed: "https://evertpot.com/atom.xml"
  jordiboggiano:
    name: "Jordi Boggiano"
    title: "Jordi Boggiano's blog"
    url: "https://seld.be/"
    feed: "https://feeds.seld.be/blog-seld"
    active: false
  beberlei:
    name: "Benjamin Eberlei"
    title: "Benjamin Eberlei's weblog"
    url: "https://beberlei.de/"
    feed: "https://beberlei.de/rss.xml"
  rdohms:
    name: "Rafael Dohms"
    title: "Rafael Dohms' blog"
    url: "https://blog.doh.ms/"
    feed: "https://blog.doh.ms/feed/"
  sitepoint:
    name: "Sitepoint"
    title: "Sitepoint"
    url: "https://www.sitepoint.com/php/"
    feed: "https://www.sitepoint.com/php/feed/"
  annafilina:
    name: "Anna Filina"
    title: "Anna Filina's weblog"
    url: "https://afilina.com/blog"
    feed: "https://afilina.com/feed"
    active: false
  ericlbarnes:
    name: "Eric L. Barnes"
    title: "Eric L. Barnes' Weblog"
    url: "https://ericlbarnes.com/"
    feed: "https://ericlbarnes.com/feed/"
  joshuathijssen:
    name: "Joshua Thijssen"
    title: "Joshua Thijssen's weblog"
    url: "https://www.adayinthelifeof.nl/"
    feed: "https://www.adayinthelifeof.nl/feed/"
    active: false
  daylerees:
    name: "Dayle Rees"
    title: "Dayle Rees' weblog"
    feed: "https://daylerees.com/rss/"
    url: "https://daylerees.com/"
  davedevelopment:
    name: "Dave Marshall"
    title: "Dave Marshall's weblog"
    feed: "https://davedevelopment.co.uk/atom.xml"
    url: "https://davedevelopment.co.uk/"
  roballen:
    name: "Rob Allen"
    title: "Rob Allen's DevNotes"
    feed: "https://akrabat.com/feed/"
    url: "https://akrabat.com/"
  gabrielaio:
    name: "Gabriela D'Ávila"
    title: "gabriela.IO"
    feed: "https://blog.gabriela.io/feed/"
    url: "https://blog.gabriela.io/"
  frankdejonge:
    name: "Frank de Jonge"
    title: "Frank de Jonge's Blog"
    feed: "https://blog.frankdejonge.nl/rss/"
    url: "https://blog.frankdejonge.nl/"
  nikic:
    name: Nikita Popov
    title: "Blog by nikic"
    feed: https://nikic.github.io/rss.xml
    url: https://nikic.github.io/
  mattallan:
    url: https://mattallan.org
    name: mattallan.org
    feed: https://mattallan.me/index.xml
    title: mattallan.org
  asked:
    name: asked.io
    feed: https://medium.com/feed/asked-io
    title: asked.io
    url: https://medium.com/asked-io
    active: true
  ocramius:
    url: https://ocramius.github.io/
    name: ocramius.github.io
    feed: https://ocramius.github.io/atom.xml
    title: ocramius.github.io
  appstract:
    url: https://medium.com/appstract?source=rss----b9b9a2ab2f0e---4
    name: Appstract - Medium
    feed: https://medium.com/feed/appstract
    title: Appstract - Medium
  archybold:
    url: https://www.archybold.com
    name: Archyblog
    feed: https://www.archybold.com/rss.xml
    title: Archyblog
  blackfire:
    url: https://blog.blackfire.io
    name: Blackfire
    feed: https://blog.blackfire.io/feed
    title: Blackfire
    active: false
  madewithlove:
    url: https://madewithlove.be/blog/
    name: blog
    feed: https://madewithlove.be/feed/
    title: blog
  bosnadev:
    url: https://bosnadev.com
    name: Bosnadev – Code Factory
    feed: https://bosnadev.com/feed/
    title: Bosnadev – Code Factory
  bram:
    url: https://www.bram.us
    name: Bram.us
    feed: https://www.bram.us/feed/
    title: Bram.us
  thishosting.rocks:
    url: https://thishosting.rocks/tag/php/
    name: ThisHosting.Rocks
    title: ThisHosting.Rocks
    feed: https://thishosting.rocks/tag/php/feed/
    compact: true
  catswhocode:
    url: https://www.catswhocode.com/blog
    name: CatsWhoCode.com
    feed: https://feeds2.feedburner.com/Catswhocode
    title: CatsWhoCode.com
    active: false
  wyrihaximus:
    url: https://blog.wyrihaximus.net/
    name: Cees-Jan Kiewiet's blog
    feed: https://blog.wyrihaximus.net/atom.xml
    title: Cees-Jan Kiewiet's blog
  christoph:
    url: https://christoph-rumpel.com
    name: christoph-rumpel.com
    feed: https://christoph-rumpel.com/feed.xml
    title: christoph-rumpel.com
  codediesel:
    url: https://www.codediesel.com
    name: code-diesel
    feed: https://www.codediesel.com/feed/
    title: code-diesel
  colinodell:
    url: https://www.colinodell.com/blog/rss.xml
    name: colinodell.com - Blog
    feed: https://www.colinodell.com/blog/rss.xml
    title: colinodell.com - Blog
  coolblue:
    url: https://devblog.coolblue.nl
    name: Coolblue Development
    feed: https://devblog.coolblue.nl/feed/
    title: Coolblue Development
  csiphp:
    url: https://csiphp.com/
    name: "CSI: PHP"
    feed: https://csiphp.com/atom.xml
    title: "CSI: PHP"
#    active: false
  derickbailey:
    url: https://derickbailey.com
    name: DerickBailey.com
    feed: https://derickbailey.com/feed/
    title: DerickBailey.com
  dev-metal:
    url: https://www.dev-metal.com
    name: Dev Metal
    feed: https://www.dev-metal.com/feed/
    title: Dev Metal
    active: false
  labnol:
    url: https://www.labnol.org
    name: Digital Inspiration Technology Blog
    feed: https://feeds.labnol.org/labnol
    title: Digital Inspiration Technology Blog
    active: false
  dracony:
    url: https://dracony.org
    name: Dracony
    feed: https://dracony.org/feed/
    title: Dracony
    active: false
  dragonbe:
    url: https://www.dragonbe.com/
    name: DragonBe's PHP blog
    feed: https://feeds.feedburner.com/dragonbe
    title: DragonBe's PHP blog
  evaldojunior:
    url: https://blog.evaldojunior.com
    name: Evaldo Junior (InFog)
    feed: https://blog.evaldojunior.com/feed.xml
    title: Evaldo Junior (InFog)
  everzet:
    url: https://everzet.com/
    name: everzet's blog
    feed: https://everzet.com/rss
    title: everzet's blog
    active: false
  facebook:
    url: https://code.facebook.com/
    name: Facebook Code
    feed: https://code.facebook.com/posts/rss
    title: Facebook Code
    active: false
  ferd:
    url: https://ferd.ca/
    name: Ferd.ca
    feed: https://ferd.ca/feed.rss
    title: Ferd.ca
  geeh:
    url: https://blog.hock.in
    name: "Gary Hockin @GeeH"
    feed: https://blog.hock.in/feed/
    title: "Gary Hockin @GeeH"

  hannesvdvreken:
    url: https://hannesvdvreken.com/
    name: Hannes Van De Vreken
    feed: https://hannesvdvreken.com/feed
    title: Hannes Van De Vreken
  harrieverveer:
    url: https://harrieverveer.nl/
    name: Harrie Verveer
    feed: https://harrieverveer.nl/rss/feed.xml
    title: Harrie Verveer
    active: false
  ieblog:
    url: https://blogs.msdn.microsoft.com/ie
    name: IEBlog
    feed: https://blogs.msdn.com/b/ie/rss.aspx
    title: IEBlog
    active: false
  ignorethecode:
    url: https://ignorethecode.net
    name: ignorethecode.net
    feed: https://feeds.feedburner.com/IgnoreTheCode
    title: ignorethecode.net
  igor:
    url: https://igor.io/
    name: igorw
    feed: https://igor.io/index.atom
    title: igorw
  intracto:
    url: https://blog.intracto.com/
    name: Intracto
    feed: https://blog.intracto.com/rss.xml
    title: Intracto
    active: false
  JasonMcCreary:
    url: https://jasonmccreary.me/
    name: Jason McCreary
    feed: https://jasonmccreary.me/feed.atom
    title: Jason McCreary
  jefclaes:
    url: https://www.jefclaes.be/
    name: Jef Claes on software and life
    feed: https://feed.jefclaes.be/jefclaes
    title: Jef Claes on software and life
    active: false
  jenssegers:
    url: https://jenssegers.com/
    name: jenssegers.be
    feed: https://jenssegers.be/rss
    title: jenssegers.be
    active: false
  joeferguson:
    url: https://www.joeferguson.me
    name: Joe Ferguson
    feed: https://joeferguson.me/blog/feed.atom
    title: Joe Ferguson
  mathiasverraes:
    url: http://verraes.net/
    name: Mathias Verraes
    feed: http://verraes.net/feed.atom
    title: Mathias Verraes
  mattbriggs:
    url: https://mattbriggs.net/
    name: Matt Briggs
    feed: https://mattbriggs.net/atom.xml
    title: Matt Briggs
    active: false
  matthewsetter:
    url: https://www.matthewsetter.com/blog/
    name: Matthew Setter
    feed: https://www.matthewsetter.com/atom.xml
    title: Matthew Setter
  mattstauffer:
    url: https://mattstauffer.co/
    name: MattStauffer.co
    feed: https://mattstauffer.co/blog/feed.atom
    title: MattStauffer.co
  michaelbrooks:
    url: https://michaelbrooks.co.uk
    name: Michael Brooks - RSS Feed
    feed: https://michaelbrooks.co.uk/rss.xml
    title: Michael Brooks - RSS Feed
  dyrynda:
    url: https://dyrynda.com.au/blog/feed
    name: Michael Dyrynda | Laravel, PHP, DevOps
    feed: https://dyrynda.com.au/blog/feed
    title: Michael Dyrynda | Laravel, PHP, DevOps
  murze:
    url: https://murze.be
    name: murze.be
    feed: https://murze.be/feed/
    title: murze.be
    compact: true
  pascalbaljetmedia:
    url: https://pascalbaljetmedia.com/rss
    name: Pascal Baljet Media - Blog
    feed: https://pascalbaljetmedia.com/rss
    title: Pascal Baljet Media - Blog
  phparch:
    url: https://www.phparch.com
    name: php[architect] - The site for PHP professionals
    feed: https://www.phparch.com/feed/
    title: php[architect] - The site for PHP professionals
  purplebooth:
    url: https://purplebooth.co.uk/
    name: Purple Booth
    feed: https://purplebooth.co.uk/index.xml
    title: Purple Booth
  stitcher.io:
    url: https://stitcher.io
    feed: https://stitcher.io/rss
    name: Stitcher.io
    title: Stitcher.io
  sebastiandedeyne:
    url: https://sebastiandedeyne.com/feed
    name: Sebastian De Deyne
    feed: https://sebastiandedeyne.com/feed
    title: Sebastian De Deyne
  simonecarletti:
    url: https://simonecarletti.com/
    name: Simone Carletti
    feed: https://simonecarletti.com/blog/feed.xml
    title: Simone Carletti
  softonsofa:
    url: https://softonsofa.com
    name: SOFTonSOFA
    feed: https://softonsofa.com/feed/
    title: SOFTonSOFA
    active: false
  barryvdh:
    url: https://medium.com/@barryvdh
    name: Barry vd. Heuvel
    feed: https://medium.com/feed/@barryvdh
    title: Barry vd. Heuvel
  stuartherbert:
    url: https://blog.stuartherbert.com/multifeed
    name: Stuart Herbert - Blog
    feed: https://blog.stuartherbert.com/rss2.xml
    title: Stuart Herbert - Blog
    active: false
  new-aesthetic:
    url: https://new-aesthetic.tumblr.com/
    name: The New Aesthetic
    feed: https://new-aesthetic.tumblr.com/rss
    title: The New Aesthetic
  stakeholderwhisperer:
    url: https://stakeholderwhisperer.com/
    name: The Stakeholder Whisperer
    feed: https://stakeholderwhisperer.com/?format=rss
    title: The Stakeholder Whisperer
    active: false
  feryn:
    url: https://blog.feryn.eu
    name: Thijs Feryn's blog
    feed: https://blog.feryn.eu/feed/
    title: Thijs Feryn's blog
  uxmyths:
    url: https://uxmyths.com/
    name: UX Myths
    feed: https://feeds.feedburner.com/uxmyths
    title: UX Myths
    active: false
  vinkla:
    url: https://vinkla.com/
    name: vinkla/xml
    feed: https://vinkla.com/feed.xml
    title: vinkla/xml
    active: false
  web-design-weekly:
    url: https://web-design-weekly.com
    name: Web Design Weekly
    feed: https://web-design-weekly.com/rss.xml
    title: Web Design Weekly
  wesbos:
    url: https://wesbos.com
    name: Wes Bos
    feed: https://feeds.feedburner.com/wesbos/ZXAx
    title: Wes Bos
  wimgodden:
    url: https://techblog.wimgodden.be
    name: Wim Godden's professional blog
    feed: https://techblog.wimgodden.be/feed/
    title: Wim Godden's professional blog
  yappa:
    url: https://tech.yappa.be/
    name: Yappa tech blog
    feed: https://tech.yappa.be/feed.atom
    title: Yappa tech blog
  yegor256:
    url: https://www.yegor256.com/
    name: Yegor Bugayenko
    feed: https://www.yegor256.com/rss.xml
    title: Yegor Bugayenko
  sandimetz:
    url: https://www.sandimetz.com/blog/
    name: Blog - Sandi Metz
    feed: https://www.sandimetz.com/blog?format=RSS
    title: Blog - Sandi Metz
  coreyhaines:
    url: https://articles.coreyhaines.com/
    name: Corey Haines
    feed: https://articles.coreyhaines.com/atom.xml
    title: Corey Haines
    active: false
  githubengineering:
    url: https://githubengineering.com/
    name: GitHub Engineering
    feed: https://githubengineering.com/atom.xml
    title: GitHub Engineering
  jaysoo:
    url: https://jaysoo.ca
    name: Jack Hsu
    feed: https://jaysoo.ca/feed.xml
    title: Jack Hsu
  jeromedalbert:
    url: https://jeromedalbert.com/
    name: Jerome's Adventures in Software
    feed: https://feeds.feedburner.com/jeromedalbert
    title: Jerome's Adventures in Software
  mathiasbynens:
    url: https://mathiasbynens.be/notes
    name: Mathias Bynens
    feed: https://mathiasbynens.be/notes.atom
    title: Mathias Bynens
  radek:
    url: https://radek.io
    name: radek.io - Articles
    feed: https://radek.io/rss.xml
    title: radek.io - Articles
  sarahmei:
    url: https://www.sarahmei.com/blog
    name: Sarah Mei
    feed: https://www.sarahmei.com/blog/feed/
    title: Sarah Mei
    active: false
  colindecarlo:
    url: https://medium.com/@colindecarlo?source=rss-88c2ac049edd------2
    name: Colin DeCarlo
    feed: https://medium.com/feed/@colindecarlo
    title: Colin DeCarlo
  ondrejmirtes:
    url: https://medium.com/@ondrejmirtes?source=rss-1ce5e2eaba6e------2
    name: Ondřej Mirtes
    feed: https://medium.com/feed/@ondrejmirtes
    title: Ondřej Mirtes
  bethtuckerlong:
    url: https://www.alittleofboth.com/
    title: A Little of Both
    name: Beth Tucker Long
    feed: https://www.alittleofboth.com/feed/
  # Feed includes no dates. Stupid Laravel:
  fideloper:
    url: https://fideloper.com
    name: Fideloper
    feed: https://fideloper.com/feed
    title: Fideloper
    # active: false
  # Feed includes no dates. Stupid Laravel:
  serversforhackers:
    url: https://serversforhackers.com
    name: Servers for Hackers
    feed: https://serversforhackers.com/feed.xml
    title: Servers for Hackers
    # active: false
  # Feed includes no dates. Stupid Laravel:
  alfrednutile:
    url: https://www.alfrednutile.info/
    name: Alfred Nutile RSS
    feed: https://alfrednutile.info/rss_full
    title: Alfred Nutile RSS
    active: false
  troyhunt:
    url: https://www.troyhunt.com/
    name: Troy Hunt
    feed: https://www.troyhunt.com/rss/
    title: Troy Hunt
  remysharp:
    url: https://remysharp.com/
    name: Remy Sharp
    feed: https://remysharp.com/feed.xml
    title: Remy Sharp's b:log
  marcoament:
    url: https://marco.org
    name: Marco Ament
    feed: https://marco.org/rss
    title: Marco Ament
  patricklouys:
    url: https://patricklouys.com
    name: Patrick Louys
    feed: https://patricklouys.com/feed.xml
    title: A software development blog


  # Frontend stuff

  keithcirkel:
    url: https://www.keithcirkel.co.uk/
    name: Keith Cirkel
    feed: https://blog.keithcirkel.co.uk/rss/
    title: Keith Cirkel
    active: false
